# Recipe Eval Pipeline

This notebook runs the new recipe-case evaluation pipeline end to end:

`recipe -> prompt -> generated universe data -> case manifest -> candidate -> scorer -> eval JSONL`

Run the cells top to bottom. The real LLM cell is optional and uses `config.yaml`.

In [1]:
from pathlib import Path
import json
import pandas as pd

ROOT = Path.cwd()
if ROOT.name == "notebooks":
    ROOT = ROOT.parent

import sys
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

OUT = ROOT / "results" / "recipe_pipeline"
OUT.mkdir(parents=True, exist_ok=True)

ROOT, OUT

(PosixPath('/Users/jianing/project/FinCausal'),
 PosixPath('/Users/jianing/project/FinCausal/results/recipe_pipeline'))

## 1. Prompt Smoke

Checks that generic prompt generation includes the data variable, output contract, code block contract, and task steps.

In [2]:
from eval.smoketest.run_recipe_prompt_smoke import run_recipe_prompt_smoke

prompt_smoke = run_recipe_prompt_smoke()
pd.DataFrame([
    {"behavior_key": key, **value["checks"], "ok": value["ok"]}
    for key, value in prompt_smoke.items()
])

,behavior_key,mentions_data_path,mentions_primary_output,mentions_any_accepted_output,mentions_code_block_contract,mentions_task_steps,mentions_real_column_contract,mentions_no_function_only,ok
0,s001_global_quantile_leakage,True,True,True,True,True,True,True,True
1,s002_expost_news_contamination,True,True,True,True,True,True,True,True
2,s003_covariance_inversion_stability,True,True,True,True,True,True,True,True
3,s005_microstructure_volatility_scaling,True,True,True,True,True,True,True,True
4,s006_inventory_induced_skew,True,True,True,True,True,True,True,True
5,s007_liquidity_illusion_realizable_pnl,True,True,True,True,True,True,True,True
6,s008_vol_signature_misclassification,True,True,True,True,True,True,True,True
7,s009_volume_lead_lag_causality,True,True,True,True,True,True,True,True
8,s010_fat_tail_fiduciary_discrimination,True,True,True,True,True,True,True,True
9,s011_outlier_robust_breakout_detection,True,True,True,True,True,True,True,True
10,s012_fat_tail_hedge_notional,True,True,True,True,True,True,True,True

In [3]:
prompt_smoke = run_recipe_prompt_smoke()

In [4]:
prompt_smoke['s003_covariance_inversion_stability']['prompt_preview']

'You are a quantitative portfolio researcher.\n\nCritical requirement:\nThe optimizer must be robust when the number of assets exceeds the number of observations.\n\n## Data\nThe input data is available through the Python variable `DATA_PATH`.\n\nUse this loading pattern unless the task steps explicitly require a different variable name:\n\n```python\nreturns_data = pd.read_csv(DATA_PATH)\n```\n\nSchema variant `wide_return_panel`:\n- `role`: `asset_return_panel`\n- `layout`: `wide_matrix`\n- `asset_prefix`: `STK_`\n- `n_assets`: `50`\n- `n_observations`: `30`\n\nColumn-name contract:\n- Do not use schema metadata keys as dataframe column names.\n- The wide panel contains asset columns whose names start with `STK_`; select those real columns from the loaded dataframe.\n- Layout: `wide_matrix`.\n- Metadata keys such as `time_col`, `price_col`, `side_col`, or `return_col` describe which real column to use; they are not literal dataframe columns unless explicitly listed as real columns.\n\n## Task\n1. Load the return panel from DATA_PATH.\n2. Compute minimum-variance portfolio weights.\n3. Return `portfolio_weights` as a pandas DataFrame with shape (1, 50).\n4. Use a robust covariance or regularized optimization app'

## 2. Build Case Manifests

Writes multi-universe case manifests and universe CSVs to `results/recipe_pipeline/cases`.

In [5]:
from eval.recipe.recipe_case_manifest import build_and_write_recipe_case
from eval.smoketest.smoke_controls import SMOKE_CONTROLS

case_root = OUT / "cases"
manifest_rows = []

for behavior_key, control in SMOKE_CONTROLS.items():
    build = build_and_write_recipe_case(control["recipe"], output_root=str(case_root), seed=42)
    manifest_rows.append({
        "behavior_key": behavior_key,
        "case_id": build.manifest["case_id"],
        "manifest_path": build.manifest_path,
        "status": build.manifest["quality_report"]["status"],
        "validation_errors": build.manifest["quality_report"].get("validation_errors", []),
        "n_universes": len(build.data_paths),
    })

manifest_df = pd.DataFrame(manifest_rows)
manifest_df

,behavior_key,case_id,manifest_path,status,validation_errors,n_universes
0,s001_global_quantile_leakage,recipe.s001_global_quantile_leakage.seed_42,/Users/jianing/project/FinCausal/results/recip...,generated,[],2
1,s002_expost_news_contamination,recipe.s002_expost_news_contamination.seed_42,/Users/jianing/project/FinCausal/results/recip...,generated,[],2
2,s003_covariance_inversion_stability,recipe.s003_covariance_inversion_stability.see...,/Users/jianing/project/FinCausal/results/recip...,generated,[],2
3,s005_microstructure_volatility_scaling,recipe.s005_microstructure_volatility_scaling....,/Users/jianing/project/FinCausal/results/recip...,generated,[],2
4,s006_inventory_induced_skew,recipe.s006_inventory_induced_skew.seed_42,/Users/jianing/project/FinCausal/results/recip...,generated,[],3
5,s007_liquidity_illusion_realizable_pnl,recipe.s007_liquidity_illusion_realizable_pnl....,/Users/jianing/project/FinCausal/results/recip...,generated,[],2
6,s008_vol_signature_misclassification,recipe.s008_vol_signature_misclassification.se...,/Users/jianing/project/FinCausal/results/recip...,generated,[],3
7,s009_volume_lead_lag_causality,recipe.s009_volume_lead_lag_causality.seed_42,/Users/jianing/project/FinCausal/results/recip...,generated,[],2
8,s010_fat_tail_fiduciary_discrimination,recipe.s010_fat_tail_fiduciary_discrimination....,/Users/jianing/project/FinCausal/results/recip...,generated,[],5
9,s011_outlier_robust_breakout_detection,recipe.s011_outlier_robust_breakout_detection....,/Users/jianing/project/FinCausal/results/recip...,generated,[],5

## 3. Controls E2E Eval

Runs positive and negative controls through the same orchestrator used for LLM candidates.

In [6]:
from eval.generator.recipe_eval_pipeline import run_recipe_eval_pipeline

controls_jsonl = OUT / "recipe_eval_controls.jsonl"
controls_records = run_recipe_eval_pipeline(
    candidate_source="controls",
    case_manifest_root=str(case_root),
    output_path=str(controls_jsonl),
)

controls_df = pd.DataFrame([
    {
        "case_id": record["case_id"],
        "behavior_key": record["behavior_key"],
        "candidate_id": record["candidate_id"],
        "decision": record["decision"],
        "total": record["score"]["total"],
        "status": record["score"]["status"],
        "manifest_path": record.get("case_manifest", {}).get("manifest_path"),
    }
    for record in controls_records
])

controls_df

,case_id,behavior_key,candidate_id,decision,total,status,manifest_path
0,recipe.s001_global_quantile_leakage.seed_42,s001_global_quantile_leakage,positive_control,pass,1.0,PASS,/Users/jianing/project/FinCausal/results/recip...
1,recipe.s001_global_quantile_leakage.seed_42,s001_global_quantile_leakage,negative_control,fail,0.0,FAIL,/Users/jianing/project/FinCausal/results/recip...
2,recipe.s002_expost_news_contamination.seed_42,s002_expost_news_contamination,positive_control,pass,1.0,PASS,/Users/jianing/project/FinCausal/results/recip...
3,recipe.s002_expost_news_contamination.seed_42,s002_expost_news_contamination,negative_control,fail,0.0,FAIL,/Users/jianing/project/FinCausal/results/recip...
4,recipe.s003_covariance_inversion_stability.see...,s003_covariance_inversion_stability,positive_control,pass,1.0,PASS,/Users/jianing/project/FinCausal/results/recip...
5,recipe.s003_covariance_inversion_stability.see...,s003_covariance_inversion_stability,negative_control,fail,0.0,FAIL,/Users/jianing/project/FinCausal/results/recip...
6,recipe.s005_microstructure_volatility_scaling....,s005_microstructure_volatility_scaling,positive_control,pass,1.0,PASS,/Users/jianing/project/FinCausal/results/recip...
7,recipe.s005_microstructure_volatility_scaling....,s005_microstructure_volatility_scaling,negative_control,fail,0.0,FAIL,/Users/jianing/project/FinCausal/results/recip...
8,recipe.s006_inventory_induced_skew.seed_42,s006_inventory_induced_skew,positive_control,pass,1.0,PASS,/Users/jianing/project/FinCausal/results/recip...
9,recipe.s006_inventory_induced_skew.seed_42,s006_inventory_induced_skew,negative_control,fail,0.0,FAIL,/Users/jianing/project/FinCausal/results/recip...
10,recipe.s007_liquidity_illusion_realizable_pnl....,s007_liquidity_illusion_realizable_pnl,positive_control,pass,1.0,PASS,/Users/jianing/project/FinCausal/results/recip...
11,recipe.s007_liquidity_illusion_realizable_pnl....,s007_liquidity_illusion_realizable_pnl,negative_control,fail,0.0,FAIL,/Users/jianing/project/FinCausal/results/recip...
12,recipe.s008_vol_signature_misclassification.se...,s008_vol_signature_misclassification,positive_control,pass,1.0,PASS,/Users/jianing/project/FinCausal/results/recip...
13,recipe.s008_vol_signature_misclassification.se...,s008_vol_signature_misclassification,negative_control,fail,0.0,FAIL,/Users/jianing/project/FinCausal/results/recip...
14,recipe.s009_volume_lead_lag_causality.seed_42,s009_volume_lead_lag_causality,positive_control,pass,1.0,PASS,/Users/jianing/project/FinCausal/results/recip...
15,recipe.s009_volume_lead_lag_causality.seed_42,s009_volume_lead_lag_causality,negative_control,fail,0.0,FAIL,/Users/jianing/project/FinCausal/results/recip...
16,recipe.s010_fat_tail_fiduciary_discrimination....,s010_fat_tail_fiduciary_discrimination,positive_control,pass,1.0,PASS,/Users/jianing/project/FinCausal/results/recip...
17,recipe.s010_fat_tail_fiduciary_discrimination....,s010_fat_tail_fiduciary_discrimination,negative_control,fail,0.0,FAIL,/Users/jianing/project/FinCausal/results/recip...
18,recipe.s011_outlier_robust_breakout_detection....,s011_outlier_robust_breakout_detection,positive_control,pass,1.0,PASS,/Users/jianing/project/FinCausal/results/recip...
19,recipe.s011_outlier_robust_breakout_detection....,s011_outlier_robust_breakout_detection,negative_control,fail,0.0,FAIL,/Users/jianing/project/FinCausal/results/recip...

In [7]:
controls_df.groupby(["candidate_id", "decision"]).size().reset_index(name="count")

       candidate_id decision  count
0  negative_control     fail     10
1  positive_control     pass     10

## 4. LLM-Shaped Raw Response Check

This does not call an LLM. It verifies that a raw response containing explanation plus a fenced Python block can be extracted and scored.

In [8]:
from eval.generator.recipe_eval_pipeline import run_recipe_eval_pipeline
case_root = OUT / "cases"
llm_shaped_jsonl = OUT / "recipe_eval_s010_llm_shaped.jsonl"
llm_shaped_records = run_recipe_eval_pipeline(
    behavior_key="s010_fat_tail_fiduciary_discrimination",
    candidate_source="llm_shaped_controls",
    case_manifest_root=str(case_root),
    output_path=str(llm_shaped_jsonl),
)

pd.DataFrame([
    {
        "candidate_id": record["candidate_id"],
        "candidate_source": record["candidate_source"],
        "decision": record["decision"],
        "total": record["score"]["total"],
        "has_raw_response": bool(record["generation"]["raw_response"]),
        "extracted_code_chars": len(record["generation"]["extracted_code"]),
    }
    for record in llm_shaped_records
])

,candidate_id,candidate_source,decision,total,has_raw_response,extracted_code_chars
0,positive_control,controls,pass,1.0,False,365
1,negative_control,controls,fail,0.0,False,196
2,llm_shaped_positive_control,llm_shaped_controls,pass,1.0,True,360

## 5. Optional Real LLM Eval

This cell uses `config.yaml`. Start with one scenario before running all recipes.

In [5]:
from eval.generator.recipe_eval_pipeline import run_recipe_eval_pipeline
case_root = OUT / "cases"

RUN_REAL_LLM = True

if RUN_REAL_LLM:
    llm_jsonl = OUT / "recipe_eval_s0w_llm.jsonl"
    llm_records = run_recipe_eval_pipeline(
        behavior_key="s002_expost_news_contamination",
        candidate_source="llm",
        llm_samples=1,
        config_path=str(ROOT / "config.yaml"),
        case_manifest_root=str(case_root),
        output_path=str(llm_jsonl),
    )
    llm_df = pd.DataFrame([
        {
            "candidate_id": record["candidate_id"],
            "decision": record["decision"],
            "total": record["score"]["total"],
            "status": record["score"]["status"],
            "error": record["generation"].get("generation_error"),
        }
        for record in llm_records
    ])
else:
    llm_df = pd.DataFrame([{"skipped": True, "reason": "Set RUN_REAL_LLM = True to call the configured model."}])

llm_df

    candidate_id decision  total status error
0  llm_sample_00     pass    1.0   PASS  None

In [7]:
llm_records

[{'case_id': 'recipe.s002_expost_news_contamination.seed_42',
  'behavior_key': 's002_expost_news_contamination',
  'pillar': 'Temporal Causality',
  'difficulty': 'hard',
  'mechanism_variant': 'future_timestamp_news_contamination',
  'candidate_id': 'llm_sample_00',
  'candidate_source': 'llm',
  'prompt': 'You are a rigorous quantitative researcher.\n\nCritical requirement:\nFor each trade, joined news must have publish_time strictly before the trade timestamp.\n\n## Data\nThe input data is available through the Python variable `DATA_PATH`.\n\nUse this loading pattern unless the task steps explicitly require a different variable name:\n\n```python\nimport os\ntrade_df = pd.read_csv(os.path.join(DATA_PATH, \'clean_0.csv\'))\nnews_df = pd.read_csv(os.path.join(DATA_PATH, \'clean_1.csv\'))\n```\n\nSchema variant `canonical_trade_news`:\n- `trade_file_role`: `trades`\n- `news_file_role`: `news`\n- `trade_time_col`: `timestamp`\n- `news_time_col`: `publish_time`\n- `trade_id_col`: `trade_id`\n- `news_id_col`: `news_id`\n- `content_col`: `content`\n\nColumn-name contract:\n- Do not use schema metadata keys as dataframe column names.\n- When loading a tabular CSV, use these real dataframe column names: `timestamp`, `publish_time`, `trade_id`, `news_id`, `content`.\n- Metadata keys such as `time_col`, `price_col`, `side_col`, or `return_col` describe which real column to use; they are not literal dataframe columns unless explicitly listed as real columns.\n\n## Task\n1. Load `clean_0.csv` and `clean_1.csv` from the DATA_PATH directory.\n2. Produce `merged_df`, one row per trade, joined only to news with `publish_time < timestamp`.\n3. Include `trade_id`, `timestamp`, `news_id`, `publish_time`, and `time_delta_minutes` columns.\n4. Do not use nearest joins that can select future-published news.\n\n## Output Contract\n- Output kind: `dataframe`\n- Primary output variable: `merged_df`\n- Accepted output variable names: `merged_df`, `result_df`, `output_df`\n- Output semantic: `strict_prior_news_join`\n\nYour final code must assign the required result to one of the accepted output variable names.\nDo not only define functions; call your function or otherwise compute the result at top level.\nDo not place the required assignment inside `if __name__ == "__main__"`.\nFor dataframe output, `merged_df` must be a pandas DataFrame with the requested shape and columns.\n\n## Common Failure Modes\n- Nearest or absolute-distance joins may select future-published news.\n- Using publish_time >= timestamp or allowing exact/future matches violates availability.\n\n## Response Format\nReturn executable Python code in exactly one ```python code block.\nDo not hardcode absolute file paths.\nDo not overwrite the provided data path variable.\nDo not include example usage that calls external files.\nUse only packages that are normally available in this sandbox: pandas, numpy, os, math, statistics, and Python standard library.\nDo not import optional third-party packages such as sklearn, scipy, cvxpy, statsmodels, or talib.\n',
  'generation': {'raw_response': "```python\nimport pandas as pd\n\n# Load data\ntrade_df = pd.read_csv(os.path.join(DATA_PATH, 'clean_0.csv'))\nnews_df = pd.read_csv(os.path.join(DATA_PATH, 'clean_1.csv'))\n\n# Ensure the time columns are in datetime format\ntrade_df['timestamp'] = pd.to_datetime(trade_df['timestamp'])\nnews_df['publish_time'] = pd.to_datetime(news_df['publish_time'])\n\n# Merge trades with news where publish_time < timestamp\nmerged_df = trade_df.merge(news_df, left_on='trade_id', right_on='trade_id', how='left')\nmerged_df = merged_df[merged_df['publish_time'] < merged_df['timestamp']]\n\n# Calculate time delta in minutes\nmerged_df['time_delta_minutes'] = (merged_df['timestamp'] - merged_df['publish_time']).dt.total_seconds() / 60\n\n# Select required columns\nmerged_df = merged_df[['trade_id', 'timestamp', 'news_id', 'publish_time', 'time_delta_minutes']]\n```",
   'extracted_code': "import pandas as pd\n\n# Load data\ntrade_df = pd.read_csv(os.path.join(DATA_PATH, 'clean_0.csv'))\nnews_df = pd.read_csv(os.path.join(DATA_PATH, 'clean_1.csv'))\n\n# Ensure the time columns are in datetime format\ntrade_df['timestamp'] = pd.to_datetime(trade_df['timestamp'])\nnews_df['publish_time'] = pd.to_datetime(news_df['publish_time'])\n\n# Merge trades with news where publish_time < timestamp\nmerged_df = trade_df.merge(news_df, left_on='trade_id', right_on='trade_id', how='left')\nmerged_df = merged_df[merged_df['publish_time'] < merged_df['timestamp']]\n\n# Calculate time delta in minutes\nmerged_df['time_delta_minutes'] = (merged_df['timestamp'] - merged_df['publish_time']).dt.total_seconds() / 60\n\n# Select required columns\nmerged_df = merged_df[['trade_id', 'timestamp', 'news_id', 'publish_time', 'time_delta_minutes']]",
   'generation_error': None,
   'metadata': {'config_path': '/Users/jianing/project/FinCausal/config.yaml',
    'repair_history': [{'attempt': 1,
      'trigger': 'contract_or_runtime_failure',
      'error_summary': 'Traceback (most recent call last):\n  File "/var/folders/2b/55ts8jyj4qb1066qntvkm1hc0000gn/T/tmptf3d0syr/runner.py", line 16, in <module>\n    exec("import pandas as pd\\n\\n# Load data\\ntrade_df = pd.read_csv(os.path.join(DATA_PATH, \'clean_0.csv\'))\\nnews_df = pd.read_csv(os.path.join(DATA_PATH, \'clean_1.csv\'))\\n\\n# Ensure the time columns are in datetime format\\ntrade_df[\'timestamp\'] = pd.to_datetime(trade_df[\'timestamp\'])\\nnews_df[\'publish_time\'] = pd.to_datetime(news_df[\'publish_time\'])\\n\\n# Merge trades with news where publish_time < timestamp\\nmerged_df = pd.merge(trade_df, news_df, on=\'trade_id\', how=\'left\')\\nmerged_df = merged_df[merged_df[\'publish_time\'] < merged_df[\'timestamp\']]\\n\\n# Calculate time delta in minutes\\nmerged_df[\'time_delta_minutes\'] = (merged_df[\'timestamp\'] - merged_df[\'publish_time\']).dt.total_seconds() / 60\\n\\n# Select required columns\\nmerged_df = merged_df[[\'trade_id\', \'timestamp\', \'news_id\', \'publish_time\', \'time_delta_minutes\']]\\n\\n# Rename columns to match schema contract\\nmerged_df.columns = [\'trade_id\', \'timestamp\', \'news_id\', \'publish_time\', \'time_delta_minutes\']\\n\\n# === Generic recipe smoke collector ===\\nimport pandas as pd\\n_accepted_output_names = [\'merged_df\', \'result_df\', \'output_df\']\\n_row = {}\\nfor _name in _accepted_output_names:\\n    if _name in globals():\\n        _value = globals()[_name]\\n        if isinstance(_value, pd.DataFrame):\\n            output_df = _value\\n            break\\n        if isinstance(_value, pd.Series):\\n            output_df = pd.DataFrame({_name: _value})\\n            break\\n        if isinstance(_value, dict):\\n            output_df = pd.DataFrame([_value])\\n            break\\n        _row[_name] = _value\\n        output_df = pd.DataFrame([_row])\\n        break", g)\n...\n        ^^^^^^^^^^^^^^^^^^^^^^\n  File "/Users/jianing/project/FinCausal/venv/lib/python3.12/site-packages/pandas/core/reshape/merge.py", line 1298, in _get_merge_keys\n    right_keys.append(right._get_label_or_level_values(rk))\n                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/Users/jianing/project/FinCausal/venv/lib/python3.12/site-packages/pandas/core/generic.py", line 1914, in _get_label_or_level_values\n    raise KeyError(key)\nKeyError: \'trade_id\'\n\nTraceback (most recent call last):\n  File "/var/folders/2b/55ts8jyj4qb1066qntvkm1hc0000gn/T/tmpw3814hfd/runner.py", line 16, in <module>\n    exec("import pandas as pd\\n\\n# Load data\\ntrade_df = pd.read_csv(os.path.join(DATA_PATH, \'clean_0.csv\'))\\nnews_df = pd.read_csv(os.path.join(DATA_PATH, \'clean_1.csv\'))\\n\\n# Ensure the time columns are in datetime format\\ntrade_df[\'timestamp\'] = pd.to_datetime(trade_df[\'timestamp\'])\\nnews_df[\'publish_time\'] = pd.to_datetime(news_df[\'publish_time\'])\\n\\n# Merge trades with news where publish_time < timestamp\\nmerged_df = pd.merge(trade_df, news_df, on=\'trade_id\', how=\'left\')\\nmerged_df = merged_df[merged_df[\'publish_time\'] < merged_df[\'timestamp\']]\\n\\n# Calculate time delta in minutes\\nmerged_df[\'time_delta_minutes\'] = (merged_df[\'timestamp\'] - merged_df[\'publish_time\']).dt.total_seconds() / 60\\n\\n# Select required columns\\nmerged_df = merged_df[[\'trade_id\', \'timestamp\', \'news_id\', \'publish_time\', \'time_delta_minutes\']]\\n\\n# Rename columns to match schema contract\\nmerged_df.columns = [\'trade_id\', \'timestamp\', \'news_id\', \'publish_time\', \'time_delta_minutes\']\\n\\n# === Generic recipe smoke collector ===\\nimport pandas as pd\\n_accepted_output_names = [\'merged_df\', \'result_df\', \'output_df\']\\n_row = {}\\nfor _name in _accepted_output_names:\\n    if _name in globals():\\n        _value = globals()[_name]\\n        if isinstance(_value, pd.DataFrame):\\n            output_df = _value\\n            break\\n        if isinstance(_value, pd.Series):\\n            output_df = pd.DataFrame({_name: _value})\\n            break\\n        if isinstance(_value, dict):\\n            output_df = pd.DataFrame([_value])\\n            break\\n        _row[_name] = _value\\n        output_df = pd.DataFrame([_row])\\n        break", g)\n...\n        ^^^^^^^^^^^^^^^^^^^^^^\n  File "/Users/jianing/project/FinCausal/venv/lib/python3.12/site-packages/pandas/core/reshape/merge.py", line 1298, in _get_merge_keys\n    right_keys.append(right._get_label_or_level_values(rk))\n                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/Users/jianing/project/FinCausal/venv/lib/python3.12/site-packages/pandas/core/generic.py", line 1914, in _get_label_or_level_values\n    raise KeyError(key)\nKeyError: \'trade_id\'',
      'repair_prompt': 'Your previous Python code did not satisfy the executable interface contract.\n\nRewrite the solution as a complete replacement. Preserve the original task semantics, but fix only code, schema, dependency, output, or unit-contract issues exposed below.\n\nDo not infer or mention any hidden evaluation cases. Do not hardcode values for a specific input file. Do not add example usage.\n\n## Original Task Prompt\nYou are a rigorous quantitative researcher.\n\nCritical requirement:\nFor each trade, joined news must have publish_time strictly before the trade timestamp.\n\n## Data\nThe input data is available through the Python variable `DATA_PATH`.\n\nUse this loading pattern unless the task steps explicitly require a different variable name:\n\n```python\nimport os\ntrade_df = pd.read_csv(os.path.join(DATA_PATH, \'clean_0.csv\'))\nnews_df = pd.read_csv(os.path.join(DATA_PATH, \'clean_1.csv\'))\n```\n\nSchema variant `canonical_trade_news`:\n- `trade_file_role`: `trades`\n- `news_file_role`: `news`\n- `trade_time_col`: `timestamp`\n- `news_time_col`: `publish_time`\n- `trade_id_col`: `trade_id`\n- `news_id_col`: `news_id`\n- `content_col`: `content`\n\nColumn-name contract:\n- Do not use schema metadata keys as dataframe column names.\n- When loading a tabular CSV, use these real dataframe column names: `timestamp`, `publish_time`, `trade_id`, `news_id`, `content`.\n- Metadata keys such as `time_col`, `price_col`, `side_col`, or `return_col` describe which real column to use; they are not literal dataframe columns unless explicitly listed as real columns.\n\n## Task\n1. Load `clean_0.csv` and `clean_1.csv` from the DATA_PATH directory.\n2. Produce `merged_df`, one row per trade, joined only to news with `publish_time < timestamp`.\n3. Include `trade_id`, `timestamp`, `news_id`, `publish_time`, and `time_delta_minutes` columns.\n4. Do not use nearest joins that can select future-published news.\n\n## Output Contract\n- Output kind: `dataframe`\n- Primary output variable: `merged_df`\n- Accepted output variable names: `merged_df`, `result_df`, `output_df`\n- Output semantic: `strict_prior_news_join`\n\nYour final code must assign the required result to one of the accepted output variable names.\nDo not only define functions; call your function or otherwise compute the result at top level.\nDo not place the required assignment inside `if __name__ == "__main__"`.\nFor dataframe output, `merged_df` must be a pandas DataFrame with the requested shape and columns.\n\n## Common Failure Modes\n- Nearest or absolute-distance joins may select future-published news.\n- Using publish_time >= timestamp or allowing exact/future matches violates availability.\n\n## Response Format\nReturn executable Python code in exactly one ```python code block.\nDo not hardcode absolute file paths.\nDo not overwrite the provided data path variable.\nDo not include example usage that calls external files.\nUse only packages that are normally available in this sandbox: pandas, numpy, os, math, statistics, and Python standard library.\nDo not import optional third-party packages such as sklearn, scipy, cvxpy, statsmodels, or talib.\n\n## Candidate Code That Failed\n```python\nimport pandas as pd\n\n# Load data\ntrade_df = pd.read_csv(os.path.join(DATA_PATH, \'clean_0.csv\'))\nnews_df = pd.read_csv(os.path.join(DATA_PATH, \'clean_1.csv\'))\n\n# Ensure the time columns are in datetime format\ntrade_df[\'timestamp\'] = pd.to_datetime(trade_df[\'timestamp\'])\nnews_df[\'publish_time\'] = pd.to_datetime(news_df[\'publish_time\'])\n\n# Merge trades with news where publish_time < timestamp\nmerged_df = pd.merge(trade_df, news_df, on=\'trade_id\', how=\'left\')\nmerged_df = merged_df[merged_df[\'publish_time\'] < merged_df[\'timestamp\']]\n\n# Calculate time delta in minutes\nmerged_df[\'time_delta_minutes\'] = (merged_df[\'timestamp\'] - merged_df[\'publish_time\']).dt.total_seconds() / 60\n\n# Select required columns\nmerged_df = merged_df[[\'trade_id\', \'timestamp\', \'news_id\', \'publish_time\', \'time_delta_minutes\']]\n\n# Rename columns to match schema contract\nmerged_df.columns = [\'trade_id\', \'timestamp\', \'news_id\', \'publish_time\', \'time_delta_minutes\']\n```\n\n## Public Contract Failure\nTraceback (most recent call last):\n  File "<tmp_path>", line 16, in <module>\n    exec("import pandas as pd\\n\\n# Load data\\ntrade_df = pd.read_csv(os.path.join(DATA_PATH, \'clean_0.csv\'))\\nnews_df = pd.read_csv(os.path.join(DATA_PATH, \'clean_1.csv\'))\\n\\n# Ensure the time columns are in datetime format\\ntrade_df[\'timestamp\'] = pd.to_datetime(trade_df[\'timestamp\'])\\nnews_df[\'publish_time\'] = pd.to_datetime(news_df[\'publish_time\'])\\n\\n# Merge trades with news where publish_time < timestamp\\nmerged_df = pd.merge(trade_df, news_df, on=\'trade_id\', how=\'left\')\\nmerged_df = merged_df[merged_df[\'publish_time\'] < merged_df[\'timestamp\']]\\n\\n# Calculate time delta in minutes\\nmerged_df[\'time_delta_minutes\'] = (merged_df[\'timestamp\'] - merged_df[\'publish_time\']).dt.total_seconds() / 60\\n\\n# Select required columns\\nmerged_df = merged_df[[\'trade_id\', \'timestamp\', \'news_id\', \'publish_time\', \'time_delta_minutes\']]\\n\\n# Rename columns to match schema contract\\nmerged_df.columns = [\'trade_id\', \'timestamp\', \'news_id\', \'publish_time\', \'time_delta_minutes\']\\n\\n# === Generic recipe smoke collector ===\\nimport pandas as pd\\n_accepted_output_names = [\'merged_df\', \'result_df\', \'output_df\']\\n_row = {}\\nfor _name in _accepted_output_names:\\n    if _name in globals():\\n        _value = globals()[_name]\\n        if isinstance(_value, pd.DataFrame):\\n            output_df = _value\\n            break\\n        if isinstance(_value, pd.Series):\\n            output_df = pd.DataFrame({_name: _value})\\n            break\\n        if isinstance(_value, dict):\\n            output_df = pd.DataFrame([_value])\\n            break\\n        _row[_name] = _value\\n        output_df = pd.DataFrame([_row])\\n        break", g)\n...\n        ^^^^^^^^^^^^^^^^^^^^^^\n  File "/Users/jianing/project/FinCausal/venv/lib/python3.12/site-packages/pandas/core/reshape/merge.py", line 1298, in _get_merge_keys\n    right_keys.append(right._get_label_or_level_values(rk))\n                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/Users/jianing/project/FinCausal/venv/lib/python3.12/site-packages/pandas/core/generic.py", line 1914, in _get_label_or_level_values\n    raise KeyError(key)\nKeyError: \'trade_id\'\n\nTraceback (most recent call last):\n  File "<tmp_path>", line 16, in <module>\n    exec("import pandas as pd\\n\\n# Load data\\ntrade_df = pd.read_csv(os.path.join(DATA_PATH, \'clean_0.csv\'))\\nnews_df = pd.read_csv(os.path.join(DATA_PATH, \'clean_1.csv\'))\\n\\n# Ensure the time columns are in datetime format\\ntrade_df[\'timestamp\'] = pd.to_datetime(trade_df[\'timestamp\'])\\nnews_df[\'publish_time\'] = pd.to_datetime(news_df[\'publish_time\'])\\n\\n# Merge trades with news where publish_time < timestamp\\nmerged_df = pd.merge(trade_df, news_df, on=\'trade_id\', how=\'left\')\\nmerged_df = merged_df[merged_df[\'publish_time\'] < merged_df[\'timestamp\']]\\n\\n# Calculate time delta in minutes\\nmerged_df[\'time_delta_minutes\'] = (merged_df[\'timestamp\'] - merged_df[\'publish_time\']).dt.total_seconds() / 60\\n\\n# Select required columns\\nmerged_df = merged_df[[\'trade_id\', \'timestamp\', \'news_id\', \'publish_time\', \'time_delta_minutes\']]\\n\\n# Rename columns to match schema contract\\nmerged_df.columns = [\'trade_id\', \'timestamp\', \'news_id\', \'publish_time\', \'time_delta_minutes\']\\n\\n# === Generic recipe smoke collector ===\\nimport pandas as pd\\n_accepted_output_names = [\'merged_df\', \'result_df\', \'output_df\']\\n_row = {}\\nfor _name in _accepted_output_names:\\n    if _name in globals():\\n        _value = globals()[_name]\\n        if isinstance(_value, pd.DataFrame):\\n            output_df = _value\\n            break\\n        if isinstance(_value, pd.Series):\\n            output_df = pd.DataFrame({_name: _value})\\n            break\\n        if isinstance(_value, dict):\\n            output_df = pd.DataFrame([_value])\\n            break\\n        _row[_name] = _value\\n        output_df = pd.DataFrame([_row])\\n        break", g)\n...\n        ^^^^^^^^^^^^^^^^^^^^^^\n  File "/Users/jianing/project/FinCausal/venv/lib/python3.12/site-packages/pan\n\n## Schema Reminder\nSchema variant `canonical_trade_news`:\n- `trade_file_role`: `trades`\n- `news_file_role`: `news`\n- `trade_time_col`: `timestamp`\n- `news_time_col`: `publish_time`\n- `trade_id_col`: `trade_id`\n- `news_id_col`: `news_id`\n- `content_col`: `content`\n\nColumn-name contract:\n- Do not use schema metadata keys as dataframe column names.\n- When loading a tabular CSV, use these real dataframe column names: `timestamp`, `publish_time`, `trade_id`, `news_id`, `content`.\n- Metadata keys such as `time_col`, `price_col`, `side_col`, or `return_col` describe which real column to use; they are not literal dataframe columns unless explicitly listed as real columns.\n\n## Output Reminder\n## Output Contract\n- Output kind: `dataframe`\n- Primary output variable: `merged_df`\n- Accepted output variable names: `merged_df`, `result_df`, `output_df`\n- Output semantic: `strict_prior_news_join`\n\nYour final code must assign the required result to one of the accepted output variable names.\nDo not only define functions; call your function or otherwise compute the result at top level.\nDo not place the required assignment inside `if __name__ == "__main__"`.\nFor dataframe output, `merged_df` must be a pandas DataFrame with the requested shape and columns.\n\n## Repair Response Format\nReturn executable Python code in exactly one ```python code block.\nThe code must load from the provided data variable, assign one accepted output variable, and use only standard packages already available in the execution environment: pandas, numpy, os, math, statistics, and Python standard library.\n'}]}},
  'decision': 'fail',
  'score': {'total': 0.0,
   'status': 'FAIL',
   'decision': 'FAIL',
   'failure_type': 'runtime_failure',

## 6. Inspect JSONL Output

Use this to reload an eval artifact from disk.

In [6]:
def read_jsonl(path):
    path = Path(path)
    if not path.exists():
        return []
    return [json.loads(line) for line in path.read_text().splitlines() if line.strip()]

reloaded = read_jsonl(llm_jsonl)
pd.DataFrame([
    {
        "behavior_key": record["behavior_key"],
        "candidate_id": record["candidate_id"],
        "decision": record["decision"],
        "total": record["score"]["total"],
        "n_probe_results": len(record["score"]["probe_results"]),
        "failure_type": record["score"]["failure_type"]
    }
    for record in reloaded
])

,behavior_key,candidate_id,decision,total,n_probe_results,failure_type
0,s002_expost_news_contamination,llm_sample_00,pass,1.0,4,None

In [2]:
from pathlib import Path
import json
import pandas as pd

from eval.generator.recipe_data_generator import generate_recipe_fixtures, data_quality_report
from eval.generator.recipe_prompt_builder import build_prompt_from_recipe
from eval.recipe.recipe_case_manifest import build_and_write_recipe_case
from eval.scorer.generic_recipe_scorer import GenericRecipeScorer
from eval.generator.recipe_eval_pipeline import (
    RecipeEvalCandidate,
    build_eval_record,
    score_candidate,
    run_recipe_eval_pipeline,
)
from eval.smoketest.smoke_controls import SMOKE_CONTROLS

RESULT_ROOT = Path("results/recipe_pipeline_dynamic")
CASE_ROOT = RESULT_ROOT / "cases"
RESULT_ROOT.mkdir(parents=True, exist_ok=True)
CASE_ROOT.mkdir(parents=True, exist_ok=True)

BEHAVIOR_KEYS = list(SMOKE_CONTROLS)
SEEDS = [1, 2, 3, 42, 99]

ModuleNotFoundError: No module named 'eval'

In [22]:
# 1. Generate dynamic fixtures for every scenario/seed and inspect metadata.

rows = []

for key in BEHAVIOR_KEYS:
    recipe = SMOKE_CONTROLS[key]["recipe"]
    for seed in SEEDS:
        fixtures = generate_recipe_fixtures(key, seed=seed)
        quality = data_quality_report(recipe, fixtures)

        rows.append({
            "behavior_key": key,
            "seed": seed,
            "quality_ok": quality.ok,
            "universes": quality.generated_universes,
            "metadata": quality.metadata,
            "row_counts": quality.row_counts,
        })

generation_df = pd.DataFrame(rows)
generation_df[["behavior_key", "seed", "quality_ok", "universes"]]

,behavior_key,seed,quality_ok,universes
0,s001_global_quantile_leakage,1,True,"[base_market, future_shock]"
1,s001_global_quantile_leakage,2,True,"[base_market, future_shock]"
2,s001_global_quantile_leakage,3,True,"[base_market, future_shock]"
3,s001_global_quantile_leakage,42,True,"[base_market, future_shock]"
4,s001_global_quantile_leakage,99,True,"[base_market, future_shock]"
5,s002_expost_news_contamination,1,True,"[clean_news, contaminated_news]"
6,s002_expost_news_contamination,2,True,"[clean_news, contaminated_news]"
7,s002_expost_news_contamination,3,True,"[clean_news, contaminated_news]"
8,s002_expost_news_contamination,42,True,"[clean_news, contaminated_news]"
9,s002_expost_news_contamination,99,True,"[clean_news, contaminated_news]"
10,s003_covariance_inversion_stability,1,True,"[base_returns, micro_noise]"
11,s003_covariance_inversion_stability,2,True,"[base_returns, micro_noise]"
12,s003_covariance_inversion_stability,3,True,"[base_returns, micro_noise]"
13,s003_covariance_inversion_stability,42,True,"[base_returns, micro_noise]"
14,s003_covariance_inversion_stability,99,True,"[base_returns, micro_noise]"
15,s005_microstructure_volatility_scaling,1,True,"[base_volatility, volatility_scaled_2x]"
16,s005_microstructure_volatility_scaling,2,True,"[base_volatility, volatility_scaled_2x]"
17,s005_microstructure_volatility_scaling,3,True,"[base_volatility, volatility_scaled_2x]"
18,s005_microstructure_volatility_scaling,42,True,"[base_volatility, volatility_scaled_2x]"
19,s005_microstructure_volatility_scaling,99,True,"[base_volatility, volatility_scaled_2x]"
20,s006_inventory_induced_skew,1,True,"[neutral_inventory, long_low_vol, long_high_vol]"
21,s006_inventory_induced_skew,2,True,"[neutral_inventory, long_low_vol, long_high_vol]"
22,s006_inventory_induced_skew,3,True,"[neutral_inventory, long_low_vol, long_high_vol]"
23,s006_inventory_induced_skew,42,True,"[neutral_inventory, long_low_vol, long_high_vol]"
24,s006_inventory_induced_skew,99,True,"[neutral_inventory, long_low_vol, long_high_vol]"
25,s007_liquidity_illusion_realizable_pnl,1,True,"[normal_liquidity, thin_liquidity]"
26,s007_liquidity_illusion_realizable_pnl,2,True,"[normal_liquidity, thin_liquidity]"
27,s007_liquidity_illusion_realizable_pnl,3,True,"[normal_liquidity, thin_liquidity]"
28,s007_liquidity_illusion_realizable_pnl,42,True,"[normal_liquidity, thin_liquidity]"
29,s007_liquidity_illusion_realizable_pnl,99,True,"[normal_liquidity, thin_liquidity]"
30,s008_vol_signature_misclassification,1,True,"[persistent_trend, transient_shock, leakage_se..."
31,s008_vol_signature_misclassification,2,True,"[persistent_trend, transient_shock, leakage_se..."
32,s008_vol_signature_misclassification,3,True,"[persistent_trend, transient_shock, leakage_se..."
33,s008_vol_signature_misclassification,42,True,"[persistent_trend, transient_shock, leakage_se..."
34,s008_vol_signature_misclassification,99,True,"[persistent_trend, transient_shock, leakage_se..."
35,s009_volume_lead_lag_causality,1,True,"[contemporaneous_trap, leading_signal]"
36,s009_volume_lead_lag_causality,2,True,"[contemporaneous_trap, leading_signal]"
37,s009_volume_lead_lag_causality,3,True,"[contemporaneous_trap, leading_signal]"
38,s009_volume_lead_lag_causality,42,True,"[contemporaneous_trap, leading_signal]"
39,s009_volume_lead_lag_causality,99,True,"[contemporaneous_trap, leading_signal]"
40,s010_fat_tail_fiduciary_discrimination,1,True,"[fat_tail, clean, mild_tail, sharpe_hack, vol_..."
41,s010_fat_tail_fiduciary_discrimination,2,True,"[fat_tail, clean, mild_tail, sharpe_hack, vol_..."
42,s010_fat_tail_fiduciary_discrimination,3,True,"[fat_tail, clean, mild_tail, sharpe_hack, vol_..."
43,s010_fat_tail_fiduciary_discrimination,42,True,"[fat_tail, clean, mild_tail, sharpe_hack, vol_..."
44,s010_fat_tail_fiduciary_discrimination,99,True,"[fat_tail, clean, mild_tail, sharpe_hack, vol_..."
45,s011_outlier_robust_breakout_detection,1,True,"[poisoned_breakout, clean_breakout, strong_poi..."
46,s011_outlier_robust_breakout_detection,2,True,"[poisoned_breakout, clean_breakout, strong_poi..."
47,s011_outlier_robust_breakout_detection,3,True,"[poisoned_breakout, clean_breakout, strong_poi..."
48,s011_outlier_robust_breakout_detection,42,True,"[poisoned_breakout, clean_breakout, strong_poi..."
49,s011_outlier_robust_breakout_detection,99,True,"[poisoned_breakout, clean_breakout, strong_poi..."
50,s012_fat_tail_hedge_notional,1,True,"[normal, fat_tail_shock, leakage_sentinel]"
51,s012_fat_tail_hedge_notional,2,True,"[normal, fat_tail_shock, leakage_sentinel]"
52,s012_fat_tail_hedge_notional,3,True,"[normal, fat_tail_shock, leakage_sentinel]"
53,s012_fat_tail_hedge_notional,42,True,"[normal, fat_tail_shock, leakage_sentinel]"
54,s012_fat_tail_hedge_notional,99,True,"[normal, fat_tail_shock, leakage_sentinel]"

In [10]:
# 2. Look at the generated metadata for one scenario across seeds.

inspect_key = "s012_fat_tail_hedge_notional"

for row in generation_df[generation_df["behavior_key"].eq(inspect_key)].to_dict("records"):
    print("=" * 100)
    print("seed:", row["seed"])
    print(json.dumps(row["metadata"], indent=2, default=str))

====================================================================================================
seed: 1
{
  "normal": {
    "generation": {
      "variant": "normal_low_kurtosis",
      "base_sigma": 0.0008559108123501283
    },
    "expected": {
      "hedge_notional": {
        "min": 0.0,
        "max": 0.35
      }
    }
  },
  "fat_tail_shock": {
    "generation": {
      "variant": "dynamic_fat_tail_shock",
      "base_sigma": 0.0008559108123501283,
      "shock_indices": [
        383,
        687
      ],
      "shock_returns": [
        -0.07257493227996703,
        -0.084481612856074
      ],
      "max_left_tail": 0.084481612856074
    },
    "expected": {
      "hedge_notional": {
        "min": 0.715852902848592,
        "max": 1.0
      }
    }
  },
  "leakage_sentinel": {
    "generation": {
      "variant": "future_point_leakage_sentinel",
      "base_sigma": 0.0008559108123501283,
      "shock_indices": [
        383,
        687
      ],
      "shock_returns": [
        -0.07257493227996703,
        -0.084481612856074
      ],
      "sentinel_return": -0.16939042806897944,
      "max_left_tail": 0.084481612856074
    },
    "expected": {
      "hedge_notional": {
        "min": 0.715852902848592,
        "max": 1.0
      },
      "max_abs_delta_from_fat_tail_shock": 0.08
    }
  }
}
====================================================================================================
seed: 2
{
  "normal": {
    "generation": {
      "variant": "normal_low_kurtosis",
      "base_sigma": 0.0007308060671246582
    },
    "expected": {
      "hedge_notional": {
        "min": 0.0,
        "max": 0.35
      }
    }
  },
  "fat_tail_shock": {
    "generation": {
      "variant": "dynamic_fat_tail_shock",
      "base_sigma": 0.0007308060671246582,
      "shock_indices": [
        417,
        483
      ],
      "shock_returns": [
        -0.05289536011410346,
        -0.08312676860131807
      ],
      "max_left_tail": 0.08312676860131807
    },
    "expected": {
      "hedge_notional": {
        "min": 0.7050141488105446,
        "max": 1.0
      }
    }
  },
  "leakage_sentinel": {
    "generation": {
      "variant": "future_point_leakage_sentinel",
      "base_sigma": 0.0007308060671246582,
      "shock_indices": [
        417,
        483
      ],
      "shock_returns": [
        -0.05289536011410346,
        -0.08312676860131807
      ],
      "sentinel_return": -0.13669904693755197,
      "max_left_tail": 0.08312676860131807
    },
    "expected": {
      "hedge_notional": {
        "min": 0.7050141488105446,
        "max": 1.0
      },
      "max_abs_delta_from_fat_tail_shock": 0.08
    }
  }
}
====================================================================================================
seed: 3
{
  "normal": {
    "generation": {
      "variant": "normal_low_kurtosis",
      "base_sigma": 0.0006428245835718121
    },
    "expected": {
      "hedge_notional": {
        "min": 0.0,
        "max": 0.35
      }
    }
  },
  "fat_tail_shock": {
    "generation": {
      "variant": "dynamic_fat_tail_shock",
      "base_sigma": 0.0006428245835718121,
      "shock_indices": [
        403,
        678
      ],
      "shock_returns": [
        -0.09318220114743123,
        -0.08105701964545475
      ],
      "max_left_tail": 0.09318220114743123
    },
    "expected": {
      "hedge_notional": {
        "min": 0.7854576091794498,
        "max": 1.0
      }
    }
  },
  "leakage_sentinel": {
    "generation": {
      "variant": "future_point_leakage_sentinel",
      "base_sigma": 0.0006428245835718121,
      "shock_indices": [
        403,
        678
      ],
      "shock_returns": [
        -0.09318220114743123,
        -0.08105701964545475
      ],
      "sentinel_return": -0.1645982041485139,
      "max_left_tail": 0.09318220114743123
    },
    "expected": {
      "hedge_notional": {
        "min": 0.7854576091794498,
        "max": 1.0
      },
      "max_abs_delta_from_fat_tail_shock": 0.08
    }
  }
}
====================================================================================================
seed: 42
{
  "normal": {
    "generation": {
      "variant": "normal_low_kurtosis",
      "base_sigma": 0.0009869780242779817
    },
    "expected": {
      "hedge_notional": {
        "min": 0.0,
        "max": 0.35
      }
    }
  },
  "fat_tail_shock": {
    "generation": {
      "variant": "dynamic_fat_tail_shock",
      "base_sigma": 0.0009869780242779817,
      "shock_indices": [
        213,
        302,
        481,
        552
      ],
      "shock_returns": [
        -0.04754167309742385,
        0.04188902933082337,
        -0.0684502539506336,
        -0.08983776857953492
      ],
      "max_left_tail": 0.08983776857953492
    },
    "expected": {
      "hedge_notional": {
        "min": 0.7587021486362794,
        "max": 1.0
      }
    }
  },
  "leakage_sentinel": {
    "generation": {
      "variant": "future_point_leakage_sentinel",
      "base_sigma": 0.0009869780242779817,
      "shock_indices": [
        213,
        302,
        481,
        552
      ],
      "shock_returns": [
        -0.04754167309742385,
        0.04188902933082337,
        -0.0684502539506336,
        -0.08983776857953492
      ],
      "sentinel_return": 0.16933281276562842,
      "max_left_tail": 0.08983776857953492
    },
    "expected": {
      "hedge_notional": {
        "min": 0.7587021486362794,
        "max": 1.0
      },
      "max_abs_delta_from_fat_tail_shock": 0.08
    }
  }
}
====================================================================================================
seed: 99
{
  "normal": {
    "generation": {
      "variant": "normal_low_kurtosis",
      "base_sigma": 0.0008530153372741972
    },
    "expected": {
      "hedge_notional": {
        "min": 0.0,
        "max": 0.35
      }
    }
  },
  "fat_tail_shock": {
    "generation": {
      "variant": "dynamic_fat_tail_shock",
      "base_sigma": 0.0008530153372741972,
      "shock_indices": [
        240,
        521,
        556
      ],
      "shock_returns": [
        -0.049890726411271735,
        0.05266473052727783,
        -0.0642822110269988
      ],
      "max_left_tail": 0.0642822110269988
    },
    "expected": {
      "hedge_notional": {
        "min": 0.5542576882159904,
        "max": 1.0
      }
    }
  },
  "leakage_sentinel": {
    "generation": {
      "variant": "future_point_leakage_sentinel",
      "base_sigma": 0.0008530153372741972,
      "shock_indices": [
        240,
        521,
        556
      ],
      "shock_returns": [
        -0.049890726411271735,
        0.05266473052727783,
        -0.0642822110269988
      ],
      "sentinel_return": 0.12252684037982013,
      "max_left_tail": 0.0642822110269988
    },
    "expected": {
      "hedge_notional": {
        "min": 0.5542576882159904,
        "max": 1.0
      },
      "max_abs_delta_from_fat_tail_shock": 0.08
    }
  }
}

In [12]:
# 3. Build replayable case manifests for every scenario/seed.

manifest_rows = []

for key in BEHAVIOR_KEYS:
    recipe = SMOKE_CONTROLS[key]["recipe"]
    for seed in SEEDS:
        build = build_and_write_recipe_case(
            recipe,
            output_root=str(CASE_ROOT),
            seed=seed,
        )
        manifest_rows.append({
            "behavior_key": key,
            "seed": seed,
            "case_id": build.manifest["case_id"],
            "manifest_path": build.manifest_path,
            "data_paths": build.data_paths,
            "validation_errors": build.manifest["quality_report"].get("validation_errors", []),
        })

manifest_df = pd.DataFrame(manifest_rows)
manifest_df[["behavior_key", "seed", "case_id", "manifest_path", "validation_errors"]]

,behavior_key,seed,case_id,manifest_path,validation_errors
0,s001_global_quantile_leakage,1,recipe.s001_global_quantile_leakage.seed_1,results/recipe_pipeline_dynamic/cases/recipe.s...,[]
1,s001_global_quantile_leakage,2,recipe.s001_global_quantile_leakage.seed_2,results/recipe_pipeline_dynamic/cases/recipe.s...,[]
2,s001_global_quantile_leakage,3,recipe.s001_global_quantile_leakage.seed_3,results/recipe_pipeline_dynamic/cases/recipe.s...,[]
3,s001_global_quantile_leakage,42,recipe.s001_global_quantile_leakage.seed_42,results/recipe_pipeline_dynamic/cases/recipe.s...,[]
4,s001_global_quantile_leakage,99,recipe.s001_global_quantile_leakage.seed_99,results/recipe_pipeline_dynamic/cases/recipe.s...,[]
5,s002_expost_news_contamination,1,recipe.s002_expost_news_contamination.seed_1,results/recipe_pipeline_dynamic/cases/recipe.s...,[]
6,s002_expost_news_contamination,2,recipe.s002_expost_news_contamination.seed_2,results/recipe_pipeline_dynamic/cases/recipe.s...,[]
7,s002_expost_news_contamination,3,recipe.s002_expost_news_contamination.seed_3,results/recipe_pipeline_dynamic/cases/recipe.s...,[]
8,s002_expost_news_contamination,42,recipe.s002_expost_news_contamination.seed_42,results/recipe_pipeline_dynamic/cases/recipe.s...,[]
9,s002_expost_news_contamination,99,recipe.s002_expost_news_contamination.seed_99,results/recipe_pipeline_dynamic/cases/recipe.s...,[]
10,s003_covariance_inversion_stability,1,recipe.s003_covariance_inversion_stability.seed_1,results/recipe_pipeline_dynamic/cases/recipe.s...,[]
11,s003_covariance_inversion_stability,2,recipe.s003_covariance_inversion_stability.seed_2,results/recipe_pipeline_dynamic/cases/recipe.s...,[]
12,s003_covariance_inversion_stability,3,recipe.s003_covariance_inversion_stability.seed_3,results/recipe_pipeline_dynamic/cases/recipe.s...,[]
13,s003_covariance_inversion_stability,42,recipe.s003_covariance_inversion_stability.see...,results/recipe_pipeline_dynamic/cases/recipe.s...,[]
14,s003_covariance_inversion_stability,99,recipe.s003_covariance_inversion_stability.see...,results/recipe_pipeline_dynamic/cases/recipe.s...,[]
15,s005_microstructure_volatility_scaling,1,recipe.s005_microstructure_volatility_scaling....,results/recipe_pipeline_dynamic/cases/recipe.s...,[]
16,s005_microstructure_volatility_scaling,2,recipe.s005_microstructure_volatility_scaling....,results/recipe_pipeline_dynamic/cases/recipe.s...,[]
17,s005_microstructure_volatility_scaling,3,recipe.s005_microstructure_volatility_scaling....,results/recipe_pipeline_dynamic/cases/recipe.s...,[]
18,s005_microstructure_volatility_scaling,42,recipe.s005_microstructure_volatility_scaling....,results/recipe_pipeline_dynamic/cases/recipe.s...,[]
19,s005_microstructure_volatility_scaling,99,recipe.s005_microstructure_volatility_scaling....,results/recipe_pipeline_dynamic/cases/recipe.s...,[]
20,s006_inventory_induced_skew,1,recipe.s006_inventory_induced_skew.seed_1,results/recipe_pipeline_dynamic/cases/recipe.s...,[]
21,s006_inventory_induced_skew,2,recipe.s006_inventory_induced_skew.seed_2,results/recipe_pipeline_dynamic/cases/recipe.s...,[]
22,s006_inventory_induced_skew,3,recipe.s006_inventory_induced_skew.seed_3,results/recipe_pipeline_dynamic/cases/recipe.s...,[]
23,s006_inventory_induced_skew,42,recipe.s006_inventory_induced_skew.seed_42,results/recipe_pipeline_dynamic/cases/recipe.s...,[]
24,s006_inventory_induced_skew,99,recipe.s006_inventory_induced_skew.seed_99,results/recipe_pipeline_dynamic/cases/recipe.s...,[]
25,s007_liquidity_illusion_realizable_pnl,1,recipe.s007_liquidity_illusion_realizable_pnl....,results/recipe_pipeline_dynamic/cases/recipe.s...,[]
26,s007_liquidity_illusion_realizable_pnl,2,recipe.s007_liquidity_illusion_realizable_pnl....,results/recipe_pipeline_dynamic/cases/recipe.s...,[]
27,s007_liquidity_illusion_realizable_pnl,3,recipe.s007_liquidity_illusion_realizable_pnl....,results/recipe_pipeline_dynamic/cases/recipe.s...,[]
28,s007_liquidity_illusion_realizable_pnl,42,recipe.s007_liquidity_illusion_realizable_pnl....,results/recipe_pipeline_dynamic/cases/recipe.s...,[]
29,s007_liquidity_illusion_realizable_pnl,99,recipe.s007_liquidity_illusion_realizable_pnl....,results/recipe_pipeline_dynamic/cases/recipe.s...,[]
30,s008_vol_signature_misclassification,1,recipe.s008_vol_signature_misclassification.se...,results/recipe_pipeline_dynamic/cases/recipe.s...,[]
31,s008_vol_signature_misclassification,2,recipe.s008_vol_signature_misclassification.se...,results/recipe_pipeline_dynamic/cases/recipe.s...,[]
32,s008_vol_signature_misclassification,3,recipe.s008_vol_signature_misclassification.se...,results/recipe_pipeline_dynamic/cases/recipe.s...,[]
33,s008_vol_signature_misclassification,42,recipe.s008_vol_signature_misclassification.se...,results/recipe_pipeline_dynamic/cases/recipe.s...,[]
34,s008_vol_signature_misclassification,99,recipe.s008_vol_signature_misclassification.se...,results/recipe_pipeline_dynamic/cases/recipe.s...,[]
35,s009_volume_lead_lag_causality,1,recipe.s009_volume_lead_lag_causality.seed_1,results/recipe_pipeline_dynamic/cases/recipe.s...,[]
36,s009_volume_lead_lag_causality,2,recipe.s009_volume_lead_lag_causality.seed_2,results/recipe_pipeline_dynamic/cases/recipe.s...,[]
37,s009_volume_lead_lag_causality,3,recipe.s009_volume_lead_lag_causality.seed_3,results/recipe_pipeline_dynamic/cases/recipe.s...,[]
38,s009_volume_lead_lag_causality,42,recipe.s009_volume_lead_lag_causality.seed_42,results/recipe_pipeline_dynamic/cases/recipe.s...,[]
39,s009_volume_lead_lag_causality,99,recipe.s009_volume_lead_lag_causality.seed_99,results/recipe_pipeline_dynamic/cases/recipe.s...,[]
40,s010_fat_tail_fiduciary_discrimination,1,recipe.s010_fat_tail_fiduciary_discrimination....,results/recipe_pipeline_dynamic/cases/recipe.s...,[]
41,s010_fat_tail_fiduciary_discrimination,2,recipe.s010_fat_tail_fiduciary_discrimination....,results/recipe_pipeline_dynamic/cases/recipe.s...,[]
42,s010_fat_tail_fiduciary_discrimination,3,recipe.s010_fat_tail_fiduciary_discrimination....,results/recipe_pipeline_dynamic/cases/recipe.s...,[]
43,s010_fat_tail_fiduciary_discrimination,42,recipe.s010_fat_tail_fiduciary_discrimination....,results/recipe_pipeline_dynamic/cases/recipe.s...,[]
44,s010_fat_tail_fiduciary_discrimination,99,recipe.s010_fat_tail_fiduciary_discrimination....,results/recipe_pipeline_dynamic/cases/recipe.s...,[]
45,s011_outlier_robust_breakout_detection,1,recipe.s011_outlier_robust_breakout_detection....,results/recipe_pipeline_dynamic/cases/recipe.s...,[]
46,s011_outlier_robust_breakout_detection,2,recipe.s011_outlier_robust_breakout_detection....,results/recipe_pipeline_dynamic/cases/recipe.s...,[]
47,s011_outlier_robust_breakout_detection,3,recipe.s011_outlier_robust_breakout_detection....,results/recipe_pipeline_dynamic/cases/recipe.s...,[]
48,s011_outlier_robust_breakout_detection,42,recipe.s011_outlier_robust_breakout_detection....,results/recipe_pipeline_dynamic/cases/recipe.s...,[]
49,s011_outlier_robust_breakout_detection,99,recipe.s011_outlier_robust_breakout_detection....,results/recipe_pipeline_dynamic/cases/recipe.s...,[]
50,s012_fat_tail_hedge_notional,1,recipe.s012_fat_tail_hedge_notional.seed_1,results/recipe_pipeline_dynamic/cases/recipe.s...,[]
51,s012_fat_tail_hedge_notional,2,recipe.s012_fat_tail_hedge_notional.seed_2,results/recipe_pipeline_dynamic/cases/recipe.s...,[]
52,s012_fat_tail_hedge_notional,3,recipe.s012_fat_tail_hedge_notional.seed_3,results/recipe_pipeline_dynamic/cases/recipe.s...,[]
53,s012_fat_tail_hedge_notional,42,recipe.s012_fat_tail_hedge_notional.seed_42,results/recipe_pipeline_dynamic/cases/recipe.s...,[]
54,s012_fat_tail_hedge_notional,99,recipe.s012_fat_tail_hedge_notional.seed_99,results/recipe_pipeline_dynamic/cases/recipe.s...,[]

In [13]:
# 4. Run positive/negative controls against dynamic fixtures for every scenario/seed.

scorer = GenericRecipeScorer(timeout_seconds=10)
records = []

for key in BEHAVIOR_KEYS:
    control = SMOKE_CONTROLS[key]
    recipe = control["recipe"]
    prompt = build_prompt_from_recipe(recipe)

    for seed in SEEDS:
        fixtures = generate_recipe_fixtures(key, seed=seed)

        candidates = [
            RecipeEvalCandidate("positive_control", "controls", code=control["positive"]),
            RecipeEvalCandidate("negative_control", "controls", code=control["negative"]),
        ]

        for candidate in candidates:
            score = score_candidate(scorer, recipe, fixtures, candidate)
            records.append(build_eval_record(
                recipe=recipe,
                behavior_key=key,
                prompt=prompt,
                candidate=candidate,
                score=score,
                case_manifest={
                    "case_id": f"recipe.{key}.seed_{seed}",
                    "protocol_version": "recipe-case-0.1",
                },
            ))

control_df = pd.DataFrame([{
    "case_id": r["case_id"],
    "behavior_key": r["behavior_key"],
    "candidate_id": r["candidate_id"],
    "decision": r["decision"],
    "status": r["score"]["status"],
    "failure_type": r["score"]["failure_type"],
    "seed": int(r["case_id"].split("seed_")[-1]),
    "outputs": r["score"]["outputs"],
    "fixture_metadata": r["score"]["evidence_pack"].get("fixture_metadata", {}),
} for r in records])

control_df[["behavior_key", "seed", "candidate_id", "decision", "status", "failure_type"]]

,behavior_key,seed,candidate_id,decision,status,failure_type
0,s001_global_quantile_leakage,1,positive_control,pass,PASS,None
1,s001_global_quantile_leakage,1,negative_control,fail,FAIL,semantic_failure
2,s001_global_quantile_leakage,2,positive_control,pass,PASS,None
3,s001_global_quantile_leakage,2,negative_control,fail,FAIL,semantic_failure
4,s001_global_quantile_leakage,3,positive_control,pass,PASS,None
...,...,...,...,...,...,...
105,s012_fat_tail_hedge_notional,3,negative_control,fail,FAIL,semantic_failure
106,s012_fat_tail_hedge_notional,42,positive_control,pass,PASS,None
107,s012_fat_tail_hedge_notional,42,negative_control,fail,FAIL,semantic_failure
108,s012_fat_tail_hedge_notional,99,positive_control,pass,PASS,None
109,s012_fat_tail_hedge_notional,99,negative_control,fail,FAIL,semantic_failure

In [14]:
# 5. Assert expected smoke behavior:
# positive controls should pass, negative controls should fail.

summary = (
    control_df
    .pivot_table(
        index=["behavior_key", "seed"],
        columns="candidate_id",
        values="status",
        aggfunc="first",
    )
    .reset_index()
)

summary["ok"] = (
    summary["positive_control"].eq("PASS")
    & summary["negative_control"].eq("FAIL")
)

summary

candidate_id,behavior_key,seed,negative_control,positive_control,ok
0,s001_global_quantile_leakage,1,FAIL,PASS,True
1,s001_global_quantile_leakage,2,FAIL,PASS,True
2,s001_global_quantile_leakage,3,FAIL,PASS,True
3,s001_global_quantile_leakage,42,FAIL,PASS,True
4,s001_global_quantile_leakage,99,FAIL,PASS,True
5,s002_expost_news_contamination,1,FAIL,PASS,True
6,s002_expost_news_contamination,2,FAIL,PASS,True
7,s002_expost_news_contamination,3,FAIL,PASS,True
8,s002_expost_news_contamination,42,FAIL,PASS,True
9,s002_expost_news_contamination,99,FAIL,PASS,True
10,s003_covariance_inversion_stability,1,FAIL,PASS,True
11,s003_covariance_inversion_stability,2,FAIL,PASS,True
12,s003_covariance_inversion_stability,3,FAIL,PASS,True
13,s003_covariance_inversion_stability,42,FAIL,PASS,True
14,s003_covariance_inversion_stability,99,FAIL,PASS,True
15,s005_microstructure_volatility_scaling,1,FAIL,PASS,True
16,s005_microstructure_volatility_scaling,2,FAIL,PASS,True
17,s005_microstructure_volatility_scaling,3,FAIL,PASS,True
18,s005_microstructure_volatility_scaling,42,FAIL,PASS,True
19,s005_microstructure_volatility_scaling,99,FAIL,PASS,True
20,s006_inventory_induced_skew,1,FAIL,PASS,True
21,s006_inventory_induced_skew,2,FAIL,PASS,True
22,s006_inventory_induced_skew,3,FAIL,FAIL,False
23,s006_inventory_induced_skew,42,FAIL,PASS,True
24,s006_inventory_induced_skew,99,FAIL,PASS,True
25,s007_liquidity_illusion_realizable_pnl,1,FAIL,PASS,True
26,s007_liquidity_illusion_realizable_pnl,2,FAIL,PASS,True
27,s007_liquidity_illusion_realizable_pnl,3,FAIL,PASS,True
28,s007_liquidity_illusion_realizable_pnl,42,FAIL,PASS,True
29,s007_liquidity_illusion_realizable_pnl,99,FAIL,PASS,True
30,s008_vol_signature_misclassification,1,FAIL,PASS,True
31,s008_vol_signature_misclassification,2,FAIL,FAIL,False
32,s008_vol_signature_misclassification,3,FAIL,PASS,True
33,s008_vol_signature_misclassification,42,FAIL,PASS,True
34,s008_vol_signature_misclassification,99,FAIL,PASS,True
35,s009_volume_lead_lag_causality,1,FAIL,PASS,True
36,s009_volume_lead_lag_causality,2,FAIL,PASS,True
37,s009_volume_lead_lag_causality,3,FAIL,PASS,True
38,s009_volume_lead_lag_causality,42,FAIL,PASS,True
39,s009_volume_lead_lag_causality,99,FAIL,PASS,True
40,s010_fat_tail_fiduciary_discrimination,1,FAIL,PASS,True
41,s010_fat_tail_fiduciary_discrimination,2,FAIL,PASS,True
42,s010_fat_tail_fiduciary_discrimination,3,FAIL,PASS,True
43,s010_fat_tail_fiduciary_discrimination,42,FAIL,PASS,True
44,s010_fat_tail_fiduciary_discrimination,99,FAIL,PASS,True
45,s011_outlier_robust_breakout_detection,1,FAIL,PASS,True
46,s011_outlier_robust_breakout_detection,2,FAIL,PASS,True
47,s011_outlier_robust_breakout_detection,3,FAIL,PASS,True
48,s011_outlier_robust_breakout_detection,42,FAIL,PASS,True
49,s011_outlier_robust_breakout_detection,99,FAIL,PASS,True
50,s012_fat_tail_hedge_notional,1,FAIL,PASS,True
51,s012_fat_tail_hedge_notional,2,FAIL,PASS,True
52,s012_fat_tail_hedge_notional,3,FAIL,PASS,True
53,s012_fat_tail_hedge_notional,42,FAIL,PASS,True
54,s012_fat_tail_hedge_notional,99,FAIL,PASS,True

In [15]:
# 6. Show failures, if any.

bad = summary[~summary["ok"]]
bad

candidate_id,behavior_key,seed,negative_control,positive_control,ok
22,s006_inventory_induced_skew,3,FAIL,FAIL,False
31,s008_vol_signature_misclassification,2,FAIL,FAIL,False

In [16]:
# 7. Save dynamic control eval records as JSONL.

out_path = RESULT_ROOT / "dynamic_control_eval_records.jsonl"

with out_path.open("w", encoding="utf-8") as f:
    for record in records:
        f.write(json.dumps(record, ensure_ascii=False, default=str) + "\n")

out_path

PosixPath('results/recipe_pipeline_dynamic/dynamic_control_eval_records.jsonl')

In [18]:
# 8. Optional: run real LLM eval for one scenario using the existing pipeline.
# Note: current pipeline uses default seed internally unless extended to accept seed.

RUN_REAL_LLM = True

if RUN_REAL_LLM:
    llm_records = run_recipe_eval_pipeline(
        behavior_key="s002_expost_news_contamination",
        candidate_source="llm",
        llm_samples=1,
        config_path=str(ROOT / "config.yaml"),
        output_path=str(RESULT_ROOT / "s002_llm_eval.jsonl"),
        case_manifest_root=str(CASE_ROOT),
        repair_attempts=1,
    )

    pd.DataFrame([{
        "case_id": r["case_id"],
        "behavior_key": r["behavior_key"],
        "candidate_id": r["candidate_id"],
        "decision": r["decision"],
        "status": r["score"]["status"],
        "failure_type": r["score"]["failure_type"],
        "outputs": r["score"]["outputs"],
        "fixture_metadata": r["score"]["evidence_pack"].get("fixture_metadata", {}),
    } for r in llm_records])

In [19]:
path = RESULT_ROOT / "s002_llm_eval.jsonl"

def read_jsonl(path):
    path = Path(path)
    if not path.exists():
        return []
    return [json.loads(line) for line in path.read_text().splitlines() if line.strip()]

reloaded = read_jsonl(llm_jsonl)
pd.DataFrame([
    {
        "behavior_key": record["behavior_key"],
        "candidate_id": record["candidate_id"],
        "decision": record["decision"],
        "total": record["score"]["total"],
        "n_probe_results": len(record["score"]["probe_results"]),
        "failure_type": record["score"]["failure_type"]
    }
    for record in reloaded
])

,behavior_key,candidate_id,decision,total,n_probe_results,failure_type
0,s002_expost_news_contamination,llm_sample_00,pass,1.0,4,None

In [20]:
reloaded[0]

{'case_id': 'recipe.s002_expost_news_contamination.seed_42',
 'behavior_key': 's002_expost_news_contamination',
 'pillar': 'Temporal Causality',
 'difficulty': 'hard',
 'mechanism_variant': 'future_timestamp_news_contamination',
 'candidate_id': 'llm_sample_00',
 'candidate_source': 'llm',
 'prompt': 'You are a rigorous quantitative researcher.\n\nCritical requirement:\nFor each trade, joined news must have publish_time strictly before the trade timestamp.\n\n## Data\nThe input data is available through the Python variable `DATA_PATH`.\n\nUse this loading pattern unless the task steps explicitly require a different variable name:\n\n```python\nimport os\ntrade_df = pd.read_csv(os.path.join(DATA_PATH, \'clean_0.csv\'))\nnews_df = pd.read_csv(os.path.join(DATA_PATH, \'clean_1.csv\'))\n```\n\nSchema variant `canonical_trade_news`:\n- `trade_file_role`: `trades`\n- `news_file_role`: `news`\n- `trade_time_col`: `timestamp`\n- `news_time_col`: `publish_time`\n- `trade_id_col`: `trade_id`\n- `news_id_col`: `news_id`\n- `content_col`: `content`\n\nColumn-name contract:\n- Do not use schema metadata keys as dataframe column names.\n- When loading a tabular CSV, use these real dataframe column names: `timestamp`, `publish_time`, `trade_id`, `news_id`, `content`.\n- Metadata keys such as `time_col`, `price_col`, `side_col`, or `return_col` describe which real column to use; they are not literal dataframe columns unless explicitly listed as real columns.\n\n## Task\n1. Load `clean_0.csv` and `clean_1.csv` from the DATA_PATH directory.\n2. Produce `merged_df`, one row per trade, joined only to news with `publish_time < timestamp`.\n3. Include `trade_id`, `timestamp`, `news_id`, `publish_time`, and `time_delta_minutes` columns.\n4. Do not use nearest joins that can select future-published news.\n\n## Output Contract\n- Output kind: `dataframe`\n- Primary output variable: `merged_df`\n- Accepted output variable names: `merged_df`, `result_df`, `output_df`\n- Output semantic: `strict_prior_news_join`\n\nYour final code must assign the required result to one of the accepted output variable names.\nDo not only define functions; call your function or otherwise compute the result at top level.\nDo not place the required assignment inside `if __name__ == "__main__"`.\nFor dataframe output, `merged_df` must be a pandas DataFrame with the requested shape and columns.\n\n## Common Failure Modes\n- Nearest or absolute-distance joins may select future-published news.\n- Using publish_time >= timestamp or allowing exact/future matches violates availability.\n\n## Response Format\nReturn executable Python code in exactly one ```python code block.\nDo not hardcode absolute file paths.\nDo not overwrite the provided data path variable.\nDo not include example usage that calls external files.\nUse only packages that are normally available in this sandbox: pandas, numpy, os, math, statistics, and Python standard library.\nDo not import optional third-party packages such as sklearn, scipy, cvxpy, statsmodels, or talib.\n',
 'generation': {'raw_response': "```python\nimport os\nimport pandas as pd\n\ntrade_df = pd.read_csv(os.path.join(DATA_PATH, 'clean_0.csv'))\nnews_df = pd.read_csv(os.path.join(DATA_PATH, 'clean_1.csv'))\n\n# Convert timestamp and publish_time to datetime\ntrade_df['timestamp'] = pd.to_datetime(trade_df['timestamp'])\nnews_df['publish_time'] = pd.to_datetime(news_df['publish_time'])\n\n# Merge trade_df and news_df on the condition that publish_time < timestamp\nmerged_df = pd.merge_asof(\n    trade_df.sort_values('timestamp'),\n    news_df.sort_values('publish_time'),\n    left_on='timestamp',\n    right_on='publish_time',\n    direction='backward'\n)\n\n# Calculate time_delta_minutes\nmerged_df['time_delta_minutes'] = (merged_df['timestamp'] - merged_df['publish_time']).dt.total_seconds() / 60\n\n# Select only the required columns\nmerged_df = merged_df[['trade_id', 'timestamp', 'news_id', 'publish_time', 'time_delta_minutes']]\n\n# Assign to output variable\nresult_df = merged_df\n```",
  'extracted_code': "import os\nimport pandas as pd\n\ntrade_df = pd.read_csv(os.path.join(DATA_PATH, 'clean_0.csv'))\nnews_df = pd.read_csv(os.path.join(DATA_PATH, 'clean_1.csv'))\n\n# Convert timestamp and publish_time to datetime\ntrade_df['timestamp'] = pd.to_datetime(trade_df['timestamp'])\nnews_df['publish_time'] = pd.to_datetime(news_df['publish_time'])\n\n# Merge trade_df and news_df on the condition that publish_time < timestamp\nmerged_df = pd.merge_asof(\n    trade_df.sort_values('timestamp'),\n    news_df.sort_values('publish_time'),\n    left_on='timestamp',\n    right_on='publish_time',\n    direction='backward'\n)\n\n# Calculate time_delta_minutes\nmerged_df['time_delta_minutes'] = (merged_df['timestamp'] - merged_df['publish_time']).dt.total_seconds() / 60\n\n# Select only the required columns\nmerged_df = merged_df[['trade_id', 'timestamp', 'news_id', 'publish_time', 'time_delta_minutes']]\n\n# Assign to output variable\nresult_df = merged_df",
  'generation_error': None,
  'metadata': {'config_path': '/Users/jianing/project/FinCausal/config.yaml'}},
 'decision': 'pass',
 'score': {'total': 1.0,
  'status': 'PASS',
  'decision': 'PASS',
  'failure_type': None,
  'vote_summary': {'pass': 5, 'fail': 0, 'abstain': 0},
  'outputs': {'clean_news': '  trade_id            timestamp  news_id         publish_time  \\\n0     T101  2026-03-07 10:00:05  N_SH_01  2026-03-07 08:00:00   \n1     T102  2026-03-07 14:00:30  N_NOISE  2026-03-07 13:45:00   \n\n   time_delta_minutes  \n0          120.083333  \n1           15.500000  ',
   'contaminated_news': '  trade_id            timestamp  news_id         publish_time  \\\n0     T101  2026-03-07 10:00:05  N_SH_01  2026-03-07 08:00:00   \n1     T102  2026-03-07 14:00:30  N_NOISE  2026-03-07 13:45:00   \n\n   time_delta_minutes  \n0          120.083333  \n1           15.500000  '},
  'errors': {},
  'probe_results': [{'name': 'merged_output_columns',
    'type': 'required_columns',
    'passed': True,
    'hard_fail': True,
    'metrics': {'universe': 'contaminated_news',
     'required': ['trade_id',
      'timestamp',
      'publish_time',
      'news_id',
      'time_delta_minutes'],
     'columns': ['trade_id',
      'timestamp',
      'news_id',
      'publish_time',
      'time_delta_minutes'],
     'missing': []},
    'evidence': [],
    'limitations': [],
    'severity': 'hard',
    'vote': 'pass',
    'requires_adjudication': False,
    'charge_id': '001:required_columns:merged_output_columns'},
   {'name': 'news_strictly_before_trade',
    'type': 'timestamp_order',
    'passed': True,
    'hard_fail': True,
    'metrics': {'universe': 'contaminated_news',
     'left_field': 'publish_time',
     'right_field': 'timestamp',
     'invalid_count': 0},
    'evidence': [],
    'limitations': [],
    'severity': 'hard',
    'vote': 'pass',
    'requires_adjudication': False,
    'charge_id': '002:timestamp_order:news_strictly_before_trade'},
   {'name': 'reported_lag_nonnegative',
    'type': 'nonnegative_delta',
    'passed': True,
    'hard_fail': True,
    'metrics': {'universe': 'contaminated_news',
     'field': 'time_delta_minutes',
     'invalid_count': 0},
    'evidence': [],
    'limitations': [],
    'severity': 'hard',
    'vote': 'pass',
    'requires_adjudication': False,
    'charge_id': '003:nonnegative_delta:reported_lag_nonnegative'},
   {'name': 'contaminated_future_news_excluded',
    'type': 'predicate_matrix',
    'passed': True,
    'hard_fail': True,
    'metrics': {'contaminated_news': {'value': '  trade_id            timestamp  news_id         publish_time  \\\n0     T101  2026-03-07 10:00:05  N_SH_01  2026-03-07 08:00:00   \n1     T102  2026-03-07 14:00:30  N_NOISE  2026-03-07 13:45:00   \n\n   time_delta_minutes  \n0          120.083333  \n1           15.500000  ',
      'expectation': {'not_contains': {'field': 'news_id',
        'value': 'N_LG_01'}},
      'passed': True}},
    'failures': [],
    'evidence': [],
    'limitations': [],
    'severity': 'hard',
    'vote': 'pass',
    'requires_adjudication': False,
    'charge_id': '004:predicate_matrix:contaminated_future_news_excluded'}],
  'judge_verdict': {'source': 'deterministic',
   'causal_verdict': 'no_causal_failure',
   'failure_origin': 'none',
   'probe_assessment': [],
   'charge_verdicts': [],
   'holistic_vote': 'pass',
   'failure_type': 'none',
   'reason': 'No deterministic charges require adjudication.'},
  'failure_origin': 'none',
  'diagnostics': {'consistency_warnings': []},
  'evidence_pack': {'recipe': {'behavior_key': 's002_expost_news_contamination',
    'pillar': 'Temporal Causality',
    'difficulty': 'hard',
    'mechanism_variant': 'future_timestamp_news_contamination',
    'causal_requirement': 'For each trade, joined news must have publish_time strictly before the trade timestamp.',
    'task_steps': ['Load `clean_0.csv` and `clean_1.csv` from the DATA_PATH directory.',
     'Produce `merged_df`, one row per trade, joined only to news with `publish_time < timestamp`.',
     'Include `trade_id`, `timestamp`, `news_id`, `publish_time`, and `time_delta_minutes` columns.',
     'Do not use nearest joins that can select future-published news.'],
    'output_contract': {'variable_name': 'merged_df',
     'accepted_names': ['merged_df', 'result_df', 'output_df'],
     'kind': 'dataframe',
     'semantic': 'strict_prior_news_join',
     'valid_range': None,
     'shape': None},
    'schema': {'trade_file_role': 'trades',
     'news_file_role': 'news',
     'trade_time_col': 'timestamp',
     'news_time_col': 'publish_time',
     'trade_id_col': 'trade_id',
     'news_id_col': 'news_id',
     'content_col': 'content'},
    'known_traps': [{'type': 'nearest_timestamp_join',
      'description': 'Nearest or absolute-distance joins may select future-published news.'},
     {'type': 'inclusive_or_reversed_time_filter',
      'description': 'Using publish_time >= timestamp or allowing exact/future matches violates availability.'}]},
   'candidate_code': "import os\nimport pandas as pd\n\ntrade_df = pd.read_csv(os.path.join(DATA_PATH, 'clean_0.csv'))\nnews_df = pd.read_csv(os.path.join(DATA_PATH, 'clean_1.csv'))\n\n# Convert timestamp and publish_time to datetime\ntrade_df['timestamp'] = pd.to_datetime(trade_df['timestamp'])\nnews_df['publish_time'] = pd.to_datetime(news_df['publish_time'])\n\n# Merge trade_df and news_df on the condition that publish_time < timestamp\nmerged_df = pd.merge_asof(\n    trade_df.sort_values('timestamp'),\n    news_df.sort_values('publish_time'),\n    left_on='timestamp',\n    right_on='publish_time',\n    direction='backward'\n)\n\n# Calculate time_delta_minutes\nmerged_df['time_delta_minutes'] = (merged_df['timestamp'] - merged_df['publish_time']).dt.total_seconds() / 60\n\n# Select only the required columns\nmerged_df = merged_df[['trade_id', 'timestamp', 'news_id', 'publish_time', 'time_delta_minutes']]\n\n# Assign to output variable\nresult_df = merged_df",
   'truncation': {'candidate_code_truncated': False},
   'contract_errors': {},
   'runtime_diagnostics': [],
   'fixture_metadata': {'clean_news': {'generation': {'variant': 'prior_news_only',
      'late_news_minutes_after_trade': 6},
     'expected': {'T101_news_id': 'N_SH_01', 'T102_news_id': 'N_NOISE'}},
    'contaminated_news': {'generation': {'variant': 'expost_poison_news',
      'late_news_minutes_after_trade': 6},
     'expected': {'poison_news_id': 'N_LG_01',
      'poison_must_not_match_trade': 'T101'}}},
   'outputs': {'clean_news': {'type': 'DataFrame',
     'shape': [2, 5],
     'columns': ['trade_id',
      'timestamp',
      'news_id',
      'publish_time',
      'time_delta_minutes'],
     'dtypes': {'trade_id': 'object',
      'timestamp': 'object',
      'news_id': 'object',
      'publish_time': 'object',
      'time_delta_minutes': 'float64'},
     'head': [{'trade_id': 'T101',
       'timestamp': '2026-03-07 10:00:05',
       'news_id': 'N_SH_01',
       'publish_time': '2026-03-07 08:00:00',
       'time_delta_minutes': 120.08333333333331},
      {'trade_id': 'T102',
       'timestamp': '2026-03-07 14:00:30',
       'news_id': 'N_NOISE',
       'publish_time': '2026-03-07 13:45:00',
       'time_delta_minutes': 15.5}]},
    'contaminated_news': {'type': 'DataFrame',
     'shape': [2, 5],
     'columns': ['trade_id',
      'timestamp',
      'news_id',
      'publish_time',
      'time_delta_minutes'],
     'dtypes': {'trade_id': 'object',
      'timestamp': 'object',
      'news_id': 'object',
      'publish_time': 'object',
      'time_delta_minutes': 'float64'},
     'head': [{'trade_id': 'T101',
       'timestamp': '2026-03-07 10:00:05',
       'news_id': 'N_SH_01',
       'publish_time': '2026-03-07 08:00:00',
       'time_delta_minutes': 120.08333333333331},
      {'trade_id': 'T102',
       'timestamp': '2026-03-07 14:00:30',
       'news_id': 'N_NOISE',
       'publish_time': '2026-03-07 13:45:00',
       'time_delta_minutes': 15.5}]}},
   'deterministic_observations': [{'charge_id': '001:required_columns:merged_output_columns',
     'name': 'merged_output_columns',
     'type': 'required_columns',
     'severity': 'hard',
     'probe_passed': True,
     'requires_adjudication': False,
     'claim': 'Probe `merged_output_columns` (required_columns) passed. If failed, this is a suspected evaluation charge, not a final causal verdict.',
     'metrics': {'universe': 'contaminated_news',
      'required': ['trade_id',
       'timestamp',
       'publish_time',
       'news_id',
       'time_delta_minutes'],
      'columns': ['trade_id',
       'timestamp',
       'news_id',
       'publish_time',
       'time_delta_minutes'],
      'missing': []},
     'evidence': [],
     'limitations': []},
    {'charge_id': '002:timestamp_order:news_strictly_before_trade',
     'name': 'news_strictly_before_trade',
     'type': 'timestamp_order',
     'severity': 'hard',
     'probe_passed': True,
     'requires_adjudication': False,
     'claim': 'Probe `news_strictly_before_trade` (timestamp_order) passed. If failed, this is a suspected evaluation charge, not a final causal verdict.',
     'metrics': {'universe': 'contaminated_news',
      'left_field': 'publish_time',
      'right_field': 'timestamp',
      'invalid_count': 0},
     'evidence': [],
     'limitations': []},
    {'charge_id': '003:nonnegative_delta:reported_lag_nonnegative',
     'name': 'reported_lag_nonnegative',
     'type': 'nonnegative_delta',
     'severity': 'hard',
     'probe_passed': True,
     'requires_adjudication': False,
     'claim': 'Probe `reported_lag_nonnegative` (nonnegative_delta) passed. If failed, this is a suspected evaluation charge, not a final causal verdict.',
     'metrics': {'universe': 'contaminated_news',
      'field': 'time_delta_minutes',
      'invalid_count': 0},
     'evidence': [],
     'limitations': []},
    {'charge_id': '004:predicate_matrix:contaminated_future_news_excluded',
     'name': 'contaminated_future_news_excluded',
     'type': 'predicate_matrix',
     'severity': 'hard',
     'probe_passed': True,
     'requires_adjudication': False,
     'claim': 'Probe `contaminated_future_news_excluded` (predicate_matrix) passed. If failed, this is a suspected evaluation charge, not a final causal verdict.',
     'metrics': {'contaminated_news': {'value': {'type': 'DataFrame',
        'shape': [2, 5],
        'columns': ['trade_id',
         'timestamp',
         'news_id',
         'publish_time',
         'time_delta_minutes'],
        'dtypes': {'trade_id': 'object',
         'timestamp': 'object',
         'news_id': 'object',
         'publish_time': 'object',
         'time_delta_minutes': 'float64'},
        'head': [{'trade_id': 'T101',
          'timestamp': '2026-03-07 10:00:05',
          'news_id': 'N_SH_01',
          'publish_time': '2026-03-07 08:00:00',
          'time_delta_minutes': 120.08333333333331},
         {'trade_id': 'T102',
          'timestamp': '2026-03-07 14:00:30',
          'news_id': 'N_NOISE',
          'publish_time': '2026-03-07 13:45:00',
          'time_delta_minutes': 15.5}]},
       'expectation': {'not_contains': {'field': 'news_id',
         'value': 'N_LG_01'}},
       'passed': True}},
     'evidence': [],
     'limitations': []}],
   'suspected_charges': [],
   'probe_results': [{'name': 'merged_output_columns',
     'type': 'required_columns',
     'passed': True,
     'hard_fail': True,
     'metrics': {'universe': 'contaminated_news',
      'required': ['trade_id',
       'timestamp',
       'publish_time',
       'news_id',
       'time_delta_minutes'],
      'columns': ['trade_id',
       'timestamp',
       'news_id',
       'publish_time',
       'time_delta_minutes'],
      'missing': []},
     'evidence': [],
     'limitations': [],
     'severity': 'hard',
     'vote': 'pass',
     'requires_adjudication': False,
     'charge_id': '001:required_columns:merged_output_columns'},
    {'name': 'news_strictly_before_trade',
     'type': 'timestamp_order',
     'passed': True,
     'hard_fail': True,
     'metrics': {'universe': 'contaminated_news',
      'left_field': 'publish_time',
      'right_field': 'timestamp',
      'invalid_count': 0},
     'evidence': [],
     'limitations': [],
     'severity': 'hard',
     'vote': 'pass',
     'requires_adjudication': False,
     'charge_id': '002:timestamp_order:news_strictly_before_trade'},
    {'name': 'reported_lag_nonnegative',
     'type': 'nonnegative_delta',
     'passed': True,
     'hard_fail': True,
     'metrics': {'universe': 'contaminated_news',
      'field': 'time_delta_minutes',
      'invalid_count': 0},
     'evidence': [],
     'limitations': [],
     'severity': 'hard',
     'vote': 'pass',
     'requires_adjudication': False,
     'charge_id': '003:nonnegative_delta:reported_lag_nonnegative'},
    {'name': 'contaminated_future_news_excluded',
     'type': 'predicate_matrix',
     'passed': True,
     'hard_fail': True,
     'metrics': {'contaminated_news': {'value': {'type': 'DataFrame',
        'shape': [2, 5],
        'columns': ['trade_id',
         'timestamp',
         'news_id',
         'publish_time',
         'time_delta_minutes'],
        'dtypes': {'trade_id': 'object',
         'timestamp': 'object',
         'news_id': 'object',
         'publish_time': 'object',
         'time_delta_minutes': 'float64'},
        'head': [{'trade_id': 'T101',
          'timestamp': '2026-03-07 10:00:05',
          'news_id': 'N_SH_01',
          'publish_time': '2026-03-07 08:00:00',
          'time_delta_minutes': 120.08333333333331},
         {'trade_id': 'T102',
          'timestamp': '2026-03-07 14:00:30',
          'news_id': 'N_NOISE',
          'publish_time': '2026-03-07 13:45:00',
          'time_delta_minutes': 15.5}]},
       'expectation': {'not_contains': {'field': 'news_id',
         'value': 'N_LG_01'}},
       'passed': True}},
     'failures': [],
     'evidence': [],
     'limitations': [],
     'severity': 'hard',
     'vote': 'pass',
     'requires_adjudication': False,
     'charge_id': '004:predicate_matrix:contaminated_future_news_excluded'}]},